-- Generated by hyprmoncfg

hl.monitor({
  output = "desc:Sharp Corporation 0x15C3",
  mode = "1920x1200@120.00",
  position = "0x0",
  scale = 1,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.workspace_rule({ workspace = "1", monitor = "desc:Sharp Corporation 0x15C3", default = true, persistent = true })
hl.workspace_rule({ workspace = "2", monitor = "desc:Sharp Corporation 0x15C3" })
hl.workspace_rule({ workspace = "3", monitor = "desc:Sharp Corporation 0x15C3" })
hl.workspace_rule({ workspace = "4", monitor = "desc:Sharp Corporation 0x15C3" })
hl.workspace_rule({ workspace = "5", monitor = "desc:Sharp Corporation 0x15C3" })
hl.workspace_rule({ workspace = "6", monitor = "desc:Sharp Corporation 0x15C3" })
hl.workspace_rule({ workspace = "7", monitor = "desc:Sharp Corporation 0x15C3" })
hl.workspace_rule({ workspace = "8", monitor = "desc:Sharp Corporation 0x15C3" })
hl.workspace_rule({ workspace = "9", monitor = "desc:Sharp Corporation 0x15C3" })
hl.workspace_rule({ workspace = "10", monitor = "desc:Sharp Corporation 0x15C3" })
