# Fonts
font_family      Hack Nerd Font
font_size        13
bold_font        auto
italic_font      auto
bold_italic_font auto

tab_bar_edge top
# tab_bar_style  powerline
# tab_powerline_style  round
# tab_separator  " | "
tab_fade 0.5 0.75 1 1


# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include current-theme.conf
# END_KITTY_THEME

### Keybinds ###
map ctrl+shift+r load_config_file

map ctrl+left previous_tab
map ctrl+right next_tab
map ctrl+shift+left move_tab_backward
map ctrl+shift+right move_tab_forward

enabled_layouts splits
map ctrl+= launch --location=hsplit
map ctrl+\ launch --location=vsplit

map ctrl+shift+f scroll_page_down
map ctrl+shift+b scroll_page_up
map ctrl+/ show_scrollback

map shift+up move_window up
map shift+left move_window left
map shift+right move_window right
map shift+down move_window down

map alt+left neighboring_window left
map alt+right neighboring_window right
map alt+up neighboring_window up
map alt+down neighboring_window down

map ctrl+alt+left resize_window narrower
map ctrl+alt+right resize_window wider
map ctrl+alt+up resize_window taller
map ctrl+alt+down resize_window shorter
map ctrl+alt+0 resize_window reset

