position = "top"
height = 24
icon_theme = "Papirus-Dark"
layer = "top"
popup_autohide = true

[[start]]
type = "workspaces"
hidden = ["special:magic"]

[[start]]
type = "focused"
icon_size = 16
truncate.mode = "middle"
truncate.length = 40
truncate.max_length = 40

[[start]]
type = "music"
player_type = "mpris"
format = "{title} / {artist}"
music_dir = "/home/jake/Music"
truncate.mode = "middle"
truncate.length = 20
truncate.max_length = 20
truncate_popup_title.mode = "end"
truncate_popup_title.length = 40
truncate_popup_title.max_length = 40
truncate_popup_artist.mode = "end"
truncate_popup_artist.length = 40
truncate_popup_artist.max_length = 40

[start.icons]
play = "󰐊"
pause = "󰏤"

[[center]]
type = "clock"

[[end]]
type = "tray"

[[end]]
type = "network_manager"
icon_size = 16
types_blacklist = ["loopback", "bridge"]
on_click_left = "kitty --class=wlctl -e wlctl"
# on_click_middle = "rfkill toggle wifi"

[end.profiles.wired_disconnected]
when = { type = "wired", state = "disconnected" }
icon = "icon:network-wired-disconnected-symbolic"

[[end]]
type = "bluetooth"
icon_size = 16
on_click_left = "kitty --class=bluetui -e bluetui"
on_click_middle = "bluetoothctl power $(bluetoothctl show | grep -q \"Powered: yes\" && echo off || echo on)"

[end.format]
not_found = ""
disabled = "󰂲"
enabled = ""
connected = " {device_alias}"
connected_battery = " {device_alias} • {device_battery_percent}%"

[end.popup]
max_height.devices = 5
header = " Enable Bluetooth"
disabled = "{adapter_status}"

[end.popup.device]
header = "{device_alias}"
header_battery = "{device_alias}"
footer = "{device_status}"
footer_battery = "{device_status} • Battery {device_battery_percent}%"

[end.adapter_status]
not_found = "No Bluetooth adapters found"
enabled = "Bluetooth enabled"
enabling = "Enabling Bluetooth..."
disabled = "Bluetooth disabled"
disabling = "Disabling Bluetooth..."

[end.device_status]
connected = "Connected"
connecting = "Connecting..."
disconnected = "Disconnect"
disconnecting = "Disconnecting..."

[[end]]
type = "volume"
format = "{icon}"
max_volume = 100
truncate = "end"
on_click_left = "kitty --class=wiremix -e wiremix -v output"

  # [end.icons]
  # volume_high = "󰕾"
  # volume_medium = "󰖀"
  # volume_low = "󰕿"
  # muted = "󰝟"

[[end]]
type = "battery"
icon_size = 16
show_if = "ls /sys/class/power_supply/ | grep --quiet 'BAT'"

[[end]]
type = "notifications"
show_count = false
icon_size = 16 # Does nothing for nerd fonts

  [end.icons]
  closed_none = "󰂜"
  open_none = "󰂚"
  open_some = "󱅫"
  closed_some = "󰅸"
  closed_dnd = "󰪓"
  open_dnd = "󰂠"
