theme {
	# color_scheme = /home/arkreddy/.config/hypr/themes/Libadwaita_Dark.colors
	color_scheme =  /home/arkreddy/.local/share/color-schemes/CatppuccinMochaBlue.colors
	#style=
	icon_theme = Papirus
	font = Inter
	#font_size =
	font_fixed = Hack
	#font_fixed_size =
}
