$text_color = rgba(cdd6f4ff)
$entry_background_color = rgba(1e1e2e11)
$entry_border_color = rgba(1e1e2e55)
$font_family = IBM Plex Sans Text
$font_family_clock = IBM Plex Sans Bold
# $font_material_symbols = Material Symbols Rounded

general {
	hide_cursor = true
	immediate_render = false
}

background {
    color = rgba(1e1e2eff)
    
    path = /home/arama/Pictures/Wallpapers/14_cat_mocha.jpg
    blur_size = 1
    blur_passes = 2
}
input-field {
    monitor =
    size = 250, 50
    outline_thickness = 2
    dots_size = 0.1
    dots_spacing = 0.3
    outer_color = $entry_border_color
    inner_color = $entry_background_color
    font_color = $text_color
    fade_on_empty = true

    position = 0, 20
    halign = center
    valign = center
}


label { # Clock
    monitor =
    text = $TIME
    color = $text_color
    font_size = 65
    font_family = $font_family_clock

    position = 0, 300
    halign = center
    valign = center
}
label { # Date
    monitor =
    text = cmd[update:5000] date +"%A, %B %d"
    color = $text_color
    font_size = 24
    font_family = $font_family_clock

    position = 0, 220
    halign = center
    valign = center
}

#label { # User
#    monitor =
#    text = $USER
#    color = $text_color
#    outline_thickness = 2
#    dots_size = 0.2 # Scale of input-field height, 0.2 - 0.8
#    dots_spacing = 0.2 # Scale of dots' absolute size, 0.0 - 1.0
#    dots_center = true
#    font_size = 20
#    font_family = $font_family
#    position = 0, 50
#    halign = center
#    valign = bottom
#}


label { # Status (battery)
    monitor =
    text = cmd[update:5000] ${XDG_CONFIG_HOME:-$HOME/.config}/hypr/scripts/battery_status.sh
    text_align = center
    color = $text_color
    font_size = 18
    font_family = $font_family

    position = 0, -180
    halign = center
    valign = top
}
