
general {
    lock_cmd = pidof hyprlock || hyprlock -q
    before_sleep_cmd = loginctl lock-session    # lock before sleep
    inhibit_sleep = 1                           # wait for beofre_sleep_cmd before sleeping
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'  # to avoid having to press a key twice to turn on the display.
}

listener {
    timeout = 300 # 5 mins
    on-timeout = brightnessctl -s set 5%
    on-resume = brightnessctl -r
}

listener {
   timeout = 420 # 7 mins
   on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'
   on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}

listener {
    timeout = 600 # 10 mins
    on-timeout = loginctl lock-session
}

listener {
   timeout = 7 # turn off screen after locking
   on-timeout = pidof hyprlock && hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'
   on-resume = pidof hyprlock && hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}

listener {
   timeout = 1200 # 20 min
   on-timeout = systemctl suspend
}
