-- Generated by hyprmoncfg

hl.monitor({
  output = "desc:Dell Inc. DELL U3223QE 2VHLBP3",
  mode = "3840x2160@60.00",
  position = "0x-1728",
  scale = 1.25,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "desc:Sharp Corporation 0x15C3",
  disabled = true,
})

hl.workspace_rule({ workspace = "1", monitor = "desc:Sharp Corporation 0x15C3" })
hl.workspace_rule({ workspace = "2", monitor = "desc:Sharp Corporation 0x15C3" })
hl.workspace_rule({ workspace = "3", monitor = "desc:Sharp Corporation 0x15C3" })
hl.workspace_rule({ workspace = "4", monitor = "desc:Sharp Corporation 0x15C3" })
hl.workspace_rule({ workspace = "5", monitor = "desc:Sharp Corporation 0x15C3" })
hl.workspace_rule({ workspace = "6", monitor = "desc:Sharp Corporation 0x15C3" })
hl.workspace_rule({ workspace = "7", monitor = "desc:Sharp Corporation 0x15C3" })
hl.workspace_rule({ workspace = "8", monitor = "desc:Sharp Corporation 0x15C3" })
hl.workspace_rule({ workspace = "9", monitor = "desc:Sharp Corporation 0x15C3" })
hl.workspace_rule({ workspace = "10", monitor = "desc:Sharp Corporation 0x15C3" })
