# Core components
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = gnome-keyring-daemon --start --components=secrets

## Polkit Agents (use one)
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
# exec-once = systemctl --user start hyprpolkitagent

exec-once = hyprpm reload
exec-once = hyprpaper
exec-once = hypridle
exec-once = clipse -listen
exec-once = waybar 
exec-once = swaync 
exec-once = swayosd-server
# exec-once = qs -c noctalia-shell
# exec-once = qs -c $qsConfig


# Unnecessary-----------------------------------------------------------
# exec-once = easyeffects --gapplication-service  # Audio effects
# exec-once = fcitx5  # Input method
# exec-once = gnome-keyring-daemon --start --components=secrets; dbus-update-activation-environment --all; 

# exec-once = dbus-update-activation-environment --all
# exec-once = sleep 1 && dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP # Some fix idk

# exec-once = swww-daemon --format xrgb  # conflicts hyprpaper
# exec-once = /usr/lib/geoclue-2.0/demos/agent & gammastep -O 4500  # automatic night light

# Old ---------------------
# needed for vscode. Exec `code --password-store=kwallet6`
# exec-once = /usr/lib/pam_kwallet_init
#---------------------
